name: mo-water-levels
type: temporal

description: Missouri water levels provided by National Weather Service.

author: Matthew Taylor
email: matt@numenta.org

timezone: America/Chicago

sources:
  - "http://water.weather.gov/ahps2/hydrograph_to_xml.php?gage=trym7&output=xml"
  - "http://water.weather.gov/ahps2/hydrograph_to_xml.php?gage=trym8&output=xml"
  - "http://water.weather.gov/ahps2/hydrograph_to_xml.php?gage=grfi2&output=xml"
  - "http://water.weather.gov/ahps2/hydrograph_to_xml.php?gage=clkm7&output=xml"
  - "http://water.weather.gov/ahps2/hydrograph_to_xml.php?gage=sclm7&output=xml"

interval: 15 minutes

expires: 6 months

fields:
  - Stage
  - Flow

metadata:
  - originator
  - name
  - id
  - generationtime
