redisEnv: REDIS_URL
riverDir: rivers

# These values can be overridden by ENV[HOST] and ENV[PORT] for deployment.
host: 'http://localhost'
port: 8085

defaults:
  data:
    html:
      limit: 500
  river:
    interval: 10 minutes
    expires: 6 months