# Please name this the same as the directory it is in.
name: twitter-511nyc
type: categorical

# Short text description of the data you are providing.
description: Tweets from @511NYC, in an attempt to get live traffic events.

author: Matthew Taylor
email: matt@numenta.org

# Timezone is important! You should use the timezone that the data is
# collected, or if time of day does not matter in the data patterns, you many
# use "UTC"
timezone: America/New_York

# A list of URLs that contain the raw data. Each of these will be polled at the
# interval specified below, and the response text will be sent to your parser.
sources:
  - https://twitter.com/511nyc

# How often should River View poll your data sources?
interval: 1 minute

# When should your collected data expire? This means that River View will store
# a time-boxed window of data. Data outside of this timebox will be flushed.
expires: 6 months

# Primary data, usually collected in one location. Should both be scalar values.
fields:
  - event_type
  - event_status
  - tweet_text
  - hashtag
  - region
  - roadway
  - county
  - direction
  - description
  - begins
  - last_updated

new: true
