name: nyc-traffic
description: New York City traffic speeds and travel times across certain paths provided by the NYDOT.
author: Matthew Taylor
email: matt@numenta.org

timezone: America/New_York

sources:
  - http://207.251.86.229/nyc-links-cams/LinkSpeedQuery.txt

interval: 10 minutes

expires: 6 months

fields:
  - Speed
  - TravelTime

properties:
  - Borough
  - linkName
  - linkId
  - linkPoints
  - Owner
  - Transcom_id
